FROM node:19.6-alpine

WORKDIR /usr/src/app

ENV NODE_ENv production

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm ci --only=production

USER node

COPY  . .

EXPOSE 3000

CMD ["node","index.js"]